### PR TITLE
feat: Streamdeck+

### PR DESCRIPTION
**Pull request by nosjo**
This adds support for the Streamdeck+ and also requires https://github.com/XeroxDev/Stream-Deck-TS-SDK/pull/17
StreamDeck_2024-08-17_23-23-25

### CODE REVIEW

**Comment by nosjo** [comment]
Right now in package.json streamdeck-typescript links to my repo but can change that when its updated on the official one

**Comment by XeroxDev** [comment]
Hey and thanks for your contribution! This looks great and I will approve and merge it after you've changed the package back to the latest streamdeck-typescript package. 
Latest version should be live now https://www.npmjs.com/package/streamdeck-typescript (v3.2.0)

**Review by XeroxDev — APPROVED** [review]
Thank you very much. LGTM! Will try to release a version today.

**Comment by XeroxDev** [comment]
@nosjo I sadly have to revert this pull request due to the new canvas package you've installed. This seems to throw errors. See https://github.com/XeroxDev/YTMD-StreamDeck/actions/runs/10441548650/job/28912825646

**Comment by nosjo** [comment]
Im using the package to load cover images of songs and resize them so i will look into doing that without it

**Comment by XeroxDev** [comment]
I would be fine with it, but for some reasons npm doesn't like this package or fails due to an NaN error. I've tried it in the actions and even local on my machine, but same errors sadly.

**Pull request merged**
